// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: avtPieFilter.h
// ****************************************************************************

#ifndef AVT_PIE_FILTER_H
#define AVT_PIE_FILTER_H


#include <avtSIMODataTreeIterator.h>
#include <PieAttributes.h>

// ****************************************************************************
//  Class: avtPieFilter
//
//  Purpose:
//      This operator is the implied operator associated with an Pie plot.
//
//      We derive it from avtSIMODataTreeIterator because we have a Single
//      Input and Multiple Outpts
//  Programmer: jody -- generated by xml2avt
//  Creation:   Wed Oct 6 11:02:10 PDT 2021
//
// ****************************************************************************

class avtPieFilter : public avtSIMODataTreeIterator
{
  public:
    avtPieFilter();
    virtual                  ~avtPieFilter();

    virtual const char       *GetType(void)        { return "avtPieFilter"; }
    virtual const char       *GetDescription(void) { return "Creating Pies"; }

 
   
  protected:
 
    PieAttributes             atts;
    virtual avtDataTree_p     ExecuteDataTree(avtDataRepresentation *);
    virtual void              UpdateDataObjectInfo(void);
    virtual avtContract_p     ModifyContract(avtContract_p);

    
};


#endif
