// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: PieAttributes.C
// ****************************************************************************

#include <PieAttributes.h>
#include <DataNode.h>
#include <DebugStream.h>

//
// Enum conversion methods for PieAttributes::GlyphStyle
//

static const char *GlyphStyle_strings[] = {
"STYLE_PIE", "STYLE_BAR", "STYLE_BOX"
};

std::string
PieAttributes::GlyphStyle_ToString(PieAttributes::GlyphStyle t)
{
    int index = int(t);
    if(index < 0 || index >= 3) index = 0;
    return GlyphStyle_strings[index];
}

std::string
PieAttributes::GlyphStyle_ToString(int t)
{
    int index = (t < 0 || t >= 3) ? 0 : t;
    return GlyphStyle_strings[index];
}

bool
PieAttributes::GlyphStyle_FromString(const std::string &s, PieAttributes::GlyphStyle &val)
{
    val = PieAttributes::STYLE_PIE;
    for(int i = 0; i < 3; ++i)
    {
        if(s == GlyphStyle_strings[i])
        {
            val = (GlyphStyle)i;
            return true;
        }
    }
    return false;
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose:
//   Init utility for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void PieAttributes::Init()
{
    iGlyphStyle = STYLE_PIE;
    iPieSectors = 120;
    fPieRadius = 1;
    fPieBorder = 0.1;
    fBarXScale = 1;
    fBarYScale = 1;
    fBarBorder = 0.1;
    fBoxXScale = 1;
    fBoxYScale = 1;
    fBoxBorder = 0.1;

    PieAttributes::SelectAll();
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose:
//   Copy utility for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void PieAttributes::Copy(const PieAttributes &obj)
{
    iGlyphStyle = obj.iGlyphStyle;
    iPieSectors = obj.iPieSectors;
    fPieRadius = obj.fPieRadius;
    fPieBorder = obj.fPieBorder;
    fBarXScale = obj.fBarXScale;
    fBarYScale = obj.fBarYScale;
    fBarBorder = obj.fBarBorder;
    fBoxXScale = obj.fBoxXScale;
    fBoxYScale = obj.fBoxYScale;
    fBoxBorder = obj.fBoxBorder;
    multiColor = obj.multiColor;
    valueNames = obj.valueNames;

    PieAttributes::SelectAll();
}

// Type map format string
const char *PieAttributes::TypeMapFormatString = PIEATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t PieAttributes::TmfsStruct = {PIEATTRIBUTES_TMFS};


// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose:
//   Default constructor for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

PieAttributes::PieAttributes() :
    AttributeSubject(PieAttributes::TypeMapFormatString)
{
    debug1 << "QHG:[PieAttributes::PieAttributes] PieAttributes created (pure): " <<this<< endl <<std::flush;
    PieAttributes::Init();
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose:
//   Constructor for the derived classes of PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

PieAttributes::PieAttributes(private_tmfs_t tmfs) :
    AttributeSubject(tmfs.tmfs)
{
    debug1 << "QHG:[PieAttributes::PieAttributes] PieAttributes created (tmf): " <<this<< endl <<std::flush;
    PieAttributes::Init();
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose:
//   Copy constructor for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

PieAttributes::PieAttributes(const PieAttributes &obj) :
    AttributeSubject(PieAttributes::TypeMapFormatString)
{
    debug1 << "QHG:[PieAttributes::PieAttributes] PieAttributes created (copy): " <<this << ", orig: " << (&obj) << endl << std::flush;
    PieAttributes::Copy(obj);
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose:
//   Copy constructor for derived classes of the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

PieAttributes::PieAttributes(const PieAttributes &obj, private_tmfs_t tmfs) :
    AttributeSubject(tmfs.tmfs)
{
    debug1 << "QHG:[PieAttributes::PieAttributes] PieAttributes created (copy2): " <<this << ", orig: " << obj<< endl <<std::flush;
    PieAttributes::Copy(obj);
}

// ****************************************************************************
// Method: PieAttributes::~PieAttributes
//
// Purpose:
//   Destructor for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

PieAttributes::~PieAttributes()
{
    debug1 << "QHG:[PieAttributes::~PieAttributes] PieAttributes deleted (names: " << GetValueNames().size() << ")" <<this<< endl <<std::flush;
    // nothing here
}

// ****************************************************************************
// Method: PieAttributes::operator =
//
// Purpose:
//   Assignment operator for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

PieAttributes&
PieAttributes::operator = (const PieAttributes &obj)
{
    if (this == &obj) return *this;

    PieAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: PieAttributes::operator ==
//
// Purpose:
//   Comparison operator == for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

bool
PieAttributes::operator == (const PieAttributes &obj) const
{
    // Create the return value
    return ((iGlyphStyle == obj.iGlyphStyle) &&
            (iPieSectors == obj.iPieSectors) &&
            (fPieRadius == obj.fPieRadius) &&
            (fPieBorder == obj.fPieBorder) &&
            (fBarXScale == obj.fBarXScale) &&
            (fBarYScale == obj.fBarYScale) &&
            (fBarBorder == obj.fBarBorder) &&
            (fBoxXScale == obj.fBoxXScale) &&
            (fBoxYScale == obj.fBoxYScale) &&
            (fBoxBorder == obj.fBoxBorder) &&
            (multiColor == obj.multiColor) &&
            (valueNames == obj.valueNames));
}

// ****************************************************************************
// Method: PieAttributes::operator !=
//
// Purpose:
//   Comparison operator != for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

bool
PieAttributes::operator != (const PieAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: PieAttributes::TypeName
//
// Purpose:
//   Type name method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

const std::string
PieAttributes::TypeName() const
{
    return "PieAttributes";
}

// ****************************************************************************
// Method: PieAttributes::CopyAttributes
//
// Purpose:
//   CopyAttributes method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

bool
PieAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const PieAttributes *tmp = (const PieAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: PieAttributes::CreateCompatible
//
// Purpose:
//   CreateCompatible method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

AttributeSubject *
PieAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new PieAttributes(*this);
    // Other cases could go here too.

    return retval;
}

// ****************************************************************************
// Method: PieAttributes::NewInstance
//
// Purpose:
//   NewInstance method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

AttributeSubject *
PieAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new PieAttributes(*this);
    else
        retval = new PieAttributes;

    return retval;
}

// ****************************************************************************
// Method: PieAttributes::SelectAll
//
// Purpose:
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
PieAttributes::SelectAll()
{
    Select(ID_iGlyphStyle, (void *)&iGlyphStyle);
    Select(ID_iPieSectors, (void *)&iPieSectors);
    Select(ID_fPieRadius,  (void *)&fPieRadius);
    Select(ID_fPieBorder,  (void *)&fPieBorder);
    Select(ID_fBarXScale,  (void *)&fBarXScale);
    Select(ID_fBarYScale,  (void *)&fBarYScale);
    Select(ID_fBarBorder,  (void *)&fBarBorder);
    Select(ID_fBoxXScale,  (void *)&fBoxXScale);
    Select(ID_fBoxYScale,  (void *)&fBoxYScale);
    Select(ID_fBoxBorder,  (void *)&fBoxBorder);
    Select(ID_multiColor,  (void *)&multiColor);
    Select(ID_valueNames,  (void *)&valueNames);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: PieAttributes::CreateNode
//
// Purpose:
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

bool
PieAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    PieAttributes defaultObject;
    bool addToParent = false;
    // Create a node for PieAttributes.
    DataNode *node = new DataNode("PieAttributes");

    if(completeSave || !FieldsEqual(ID_iGlyphStyle, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("iGlyphStyle", GlyphStyle_ToString(iGlyphStyle)));
    }

    if(completeSave || !FieldsEqual(ID_iPieSectors, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("iPieSectors", iPieSectors));
    }

    if(completeSave || !FieldsEqual(ID_fPieRadius, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fPieRadius", fPieRadius));
    }

    if(completeSave || !FieldsEqual(ID_fPieBorder, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fPieBorder", fPieBorder));
    }

    if(completeSave || !FieldsEqual(ID_fBarXScale, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fBarXScale", fBarXScale));
    }

    if(completeSave || !FieldsEqual(ID_fBarYScale, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fBarYScale", fBarYScale));
    }

    if(completeSave || !FieldsEqual(ID_fBarBorder, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fBarBorder", fBarBorder));
    }

    if(completeSave || !FieldsEqual(ID_fBoxXScale, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fBoxXScale", fBoxXScale));
    }

    if(completeSave || !FieldsEqual(ID_fBoxYScale, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fBoxYScale", fBoxYScale));
    }

    if(completeSave || !FieldsEqual(ID_fBoxBorder, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fBoxBorder", fBoxBorder));
    }

    if(completeSave || !FieldsEqual(ID_multiColor, &defaultObject))
    {
        DataNode *multiColorNode = new DataNode("multiColor");
        if(multiColor.CreateNode(multiColorNode, completeSave, false))
        {
            addToParent = true;
            node->AddNode(multiColorNode);
        }
        else
            delete multiColorNode;
    }

    if(completeSave || !FieldsEqual(ID_valueNames, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("valueNames", valueNames));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: PieAttributes::SetFromNode
//
// Purpose:
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
PieAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("PieAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("iGlyphStyle")) != 0)
    {
        // Allow enums to be int or string in the config file
        if(node->GetNodeType() == INT_NODE)
        {
            int ival = node->AsInt();
            if(ival >= 0 && ival < 3)
                SetIGlyphStyle(GlyphStyle(ival));
        }
        else if(node->GetNodeType() == STRING_NODE)
        {
            GlyphStyle value;
            if(GlyphStyle_FromString(node->AsString(), value))
                SetIGlyphStyle(value);
        }
    }
    if((node = searchNode->GetNode("iPieSectors")) != 0)
        SetIPieSectors(node->AsInt());
    if((node = searchNode->GetNode("fPieRadius")) != 0)
        SetFPieRadius(node->AsFloat());
    if((node = searchNode->GetNode("fPieBorder")) != 0)
        SetFPieBorder(node->AsFloat());
    if((node = searchNode->GetNode("fBarXScale")) != 0)
        SetFBarXScale(node->AsFloat());
    if((node = searchNode->GetNode("fBarYScale")) != 0)
        SetFBarYScale(node->AsFloat());
    if((node = searchNode->GetNode("fBarBorder")) != 0)
        SetFBarBorder(node->AsFloat());
    if((node = searchNode->GetNode("fBoxXScale")) != 0)
        SetFBoxXScale(node->AsFloat());
    if((node = searchNode->GetNode("fBoxYScale")) != 0)
        SetFBoxYScale(node->AsFloat());
    if((node = searchNode->GetNode("fBoxBorder")) != 0)
        SetFBoxBorder(node->AsFloat());
    if((node = searchNode->GetNode("multiColor")) != 0)
        multiColor.SetFromNode(node);
    if((node = searchNode->GetNode("valueNames")) != 0)
        SetValueNames(node->AsStringVector());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
PieAttributes::SetIGlyphStyle(PieAttributes::GlyphStyle iGlyphStyle_)
{
    iGlyphStyle = iGlyphStyle_;
    Select(ID_iGlyphStyle, (void *)&iGlyphStyle);
}

void
PieAttributes::SetIPieSectors(int iPieSectors_)
{
    iPieSectors = iPieSectors_;
    Select(ID_iPieSectors, (void *)&iPieSectors);
}

void
PieAttributes::SetFPieRadius(float fPieRadius_)
{
    fPieRadius = fPieRadius_;
    Select(ID_fPieRadius, (void *)&fPieRadius);
}

void
PieAttributes::SetFPieBorder(float fPieBorder_)
{
    fPieBorder = fPieBorder_;
    Select(ID_fPieBorder, (void *)&fPieBorder);
}

void
PieAttributes::SetFBarXScale(float fBarXScale_)
{
    fBarXScale = fBarXScale_;
    Select(ID_fBarXScale, (void *)&fBarXScale);
}

void
PieAttributes::SetFBarYScale(float fBarYScale_)
{
    fBarYScale = fBarYScale_;
    Select(ID_fBarYScale, (void *)&fBarYScale);
}

void
PieAttributes::SetFBarBorder(float fBarBorder_)
{
    fBarBorder = fBarBorder_;
    Select(ID_fBarBorder, (void *)&fBarBorder);
}

void
PieAttributes::SetFBoxXScale(float fBoxXScale_)
{
    fBoxXScale = fBoxXScale_;
    Select(ID_fBoxXScale, (void *)&fBoxXScale);
}

void
PieAttributes::SetFBoxYScale(float fBoxYScale_)
{
    fBoxYScale = fBoxYScale_;
    Select(ID_fBoxYScale, (void *)&fBoxYScale);
}

void
PieAttributes::SetFBoxBorder(float fBoxBorder_)
{
    fBoxBorder = fBoxBorder_;
    Select(ID_fBoxBorder, (void *)&fBoxBorder);
}

void
PieAttributes::SetMultiColor(const ColorAttributeList &multiColor_)
{
    multiColor = multiColor_;
    Select(ID_multiColor, (void *)&multiColor);
}

void
PieAttributes::SetValueNames(const stringVector &valueNames_)
{
    valueNames = valueNames_;
    Select(ID_valueNames, (void *)&valueNames);
}


///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

PieAttributes::GlyphStyle
PieAttributes::GetIGlyphStyle() const
{
    return GlyphStyle(iGlyphStyle);
}

int
PieAttributes::GetIPieSectors() const
{
    return iPieSectors;
}

float
PieAttributes::GetFPieRadius() const
{
    return fPieRadius;
}

float
PieAttributes::GetFPieBorder() const
{
    return fPieBorder;
}

float
PieAttributes::GetFBarXScale() const
{
    return fBarXScale;
}

float
PieAttributes::GetFBarYScale() const
{
    return fBarYScale;
}

float
PieAttributes::GetFBarBorder() const
{
    return fBarBorder;
}

float
PieAttributes::GetFBoxXScale() const
{
    return fBoxXScale;
}

float
PieAttributes::GetFBoxYScale() const
{
    return fBoxYScale;
}

float
PieAttributes::GetFBoxBorder() const
{
    return fBoxBorder;
}

const ColorAttributeList &
PieAttributes::GetMultiColor() const
{
    return multiColor;
}

ColorAttributeList &
PieAttributes::GetMultiColor()
{
    return multiColor;
}

const stringVector &
PieAttributes::GetValueNames() const
{
    return valueNames;
}

stringVector &
PieAttributes::GetValueNames()
{
    return valueNames;
}

///////////////////////////////////////////////////////////////////////////////
// Select property methods
///////////////////////////////////////////////////////////////////////////////

void
PieAttributes::SelectMultiColor()
{
    Select(ID_multiColor, (void *)&multiColor);
}

void
PieAttributes::SelectValueNames()
{
    Select(ID_valueNames, (void *)&valueNames);
}


///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: PieAttributes::GetFieldName
//
// Purpose:
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

std::string
PieAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_iGlyphStyle: return "iGlyphStyle";
    case ID_iPieSectors: return "iPieSectors";
    case ID_fPieRadius:  return "fPieRadius";
    case ID_fPieBorder:  return "fPieBorder";
    case ID_fBarXScale:  return "fBarXScale";
    case ID_fBarYScale:  return "fBarYScale";
    case ID_fBarBorder:  return "fBarBorder";
    case ID_fBoxXScale:  return "fBoxXScale";
    case ID_fBoxYScale:  return "fBoxYScale";
    case ID_fBoxBorder:  return "fBoxBorder";
    case ID_multiColor:  return "multiColor";
    case ID_valueNames:  return "valueNames";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: PieAttributes::GetFieldType
//
// Purpose:
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

AttributeGroup::FieldType
PieAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_iGlyphStyle: return FieldType_enum;
    case ID_iPieSectors: return FieldType_int;
    case ID_fPieRadius:  return FieldType_float;
    case ID_fPieBorder:  return FieldType_float;
    case ID_fBarXScale:  return FieldType_float;
    case ID_fBarYScale:  return FieldType_float;
    case ID_fBarBorder:  return FieldType_float;
    case ID_fBoxXScale:  return FieldType_float;
    case ID_fBoxYScale:  return FieldType_float;
    case ID_fBoxBorder:  return FieldType_float;
    case ID_multiColor:  return FieldType_att;
    case ID_valueNames:  return FieldType_stringVector;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: PieAttributes::GetFieldTypeName
//
// Purpose:
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

std::string
PieAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_iGlyphStyle: return "enum";
    case ID_iPieSectors: return "int";
    case ID_fPieRadius:  return "float";
    case ID_fPieBorder:  return "float";
    case ID_fBarXScale:  return "float";
    case ID_fBarYScale:  return "float";
    case ID_fBarBorder:  return "float";
    case ID_fBoxXScale:  return "float";
    case ID_fBoxYScale:  return "float";
    case ID_fBoxBorder:  return "float";
    case ID_multiColor:  return "att";
    case ID_valueNames:  return "stringVector";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: PieAttributes::FieldsEqual
//
// Purpose:
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

bool
PieAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const PieAttributes &obj = *((const PieAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_iGlyphStyle:
        {  // new scope
        retval = (iGlyphStyle == obj.iGlyphStyle);
        }
        break;
    case ID_iPieSectors:
        {  // new scope
        retval = (iPieSectors == obj.iPieSectors);
        }
        break;
    case ID_fPieRadius:
        {  // new scope
        retval = (fPieRadius == obj.fPieRadius);
        }
        break;
    case ID_fPieBorder:
        {  // new scope
        retval = (fPieBorder == obj.fPieBorder);
        }
        break;
    case ID_fBarXScale:
        {  // new scope
        retval = (fBarXScale == obj.fBarXScale);
        }
        break;
    case ID_fBarYScale:
        {  // new scope
        retval = (fBarYScale == obj.fBarYScale);
        }
        break;
    case ID_fBarBorder:
        {  // new scope
        retval = (fBarBorder == obj.fBarBorder);
        }
        break;
    case ID_fBoxXScale:
        {  // new scope
        retval = (fBoxXScale == obj.fBoxXScale);
        }
        break;
    case ID_fBoxYScale:
        {  // new scope
        retval = (fBoxYScale == obj.fBoxYScale);
        }
        break;
    case ID_fBoxBorder:
        {  // new scope
        retval = (fBoxBorder == obj.fBoxBorder);
        }
        break;
    case ID_multiColor:
        {  // new scope
        retval = (multiColor == obj.multiColor);
        }
        break;
    case ID_valueNames:
        {  // new scope
        retval = (valueNames == obj.valueNames);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

//--------------------------------------------------------------------
// ChangesRequireRecalculation
//   check if a attribute has changed which requires a recalculation.
//   currently, only changes in fScale1 entail recalculation
//
bool
PieAttributes::ChangesRequireRecalculation(const PieAttributes &obj)
{
    return true;
}

