// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: PiePluginInfo.C
// ****************************************************************************

#include <PiePluginInfo.h>
#include <PieAttributes.h>

#include <visit-config.h>
VISIT_PLUGIN_VERSION(Pie,PLOT_EXPORT)

VISIT_PLOT_PLUGIN_ENTRY(Pie,General)

// ****************************************************************************
//  Method: PieGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the plot plugin.
//
//  Returns:    A pointer to the name of the plot plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
PieGeneralPluginInfo::GetName() const
{
    return "Pie";
}

// ****************************************************************************
//  Method: PieGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the plot plugin.
//
//  Returns:    A pointer to the version of the plot plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
PieGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: PieGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the plot plugin.
//
//  Returns:    A pointer to the id of the plot plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
PieGeneralPluginInfo::GetID() const
{
    return "Pie_1.0";
}
// ****************************************************************************
//  Method: PieGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
PieGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
