// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ************************************************************************* //
//  File:  PieScriptingPluginInfo.C
// ************************************************************************* //
#include <PyPieAttributes.h>
#include <PiePluginInfo.h>

VISIT_PLOT_PLUGIN_ENTRY(Pie,Scripting)

// ****************************************************************************
// Method: PieScriptingPluginInfo::InitializePlugin
//
// Purpose:
//   Calls the initialization function for the plugin.
//
// Arguments:
//   subj    : A pointer to the plugin's state object.
//   data    : A pointer to data to be used by the observer function.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
PieScriptingPluginInfo::InitializePlugin(AttributeSubject *subj,
    void *data)
{
    PyPieAttributes_StartUp((PieAttributes *)subj, data);
}

// ****************************************************************************
// Method: PieScriptingPluginInfo::GetMethodTable
//
// Purpose:
//   Returns a pointer to the plugin's Python method table. These methods are
//   added to the top-level visit module's methods.
//
// Arguments:
//   nMethods : Returns the number of methods in the method table.
//
// Returns:    A pointer to the method table.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void *
PieScriptingPluginInfo::GetMethodTable(int *nMethods)
{
    return PyPieAttributes_GetMethodTable(nMethods);
}

// ****************************************************************************
// Method: PieScriptingPluginInfo::TypesMatch
//
// Purpose:
//   Returns whether or not the input PyObject is Pie plot attributes.
//
// Arguments:
//   pyobject : A PyObject cast to void*.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

bool
PieScriptingPluginInfo::TypesMatch(void *pyobject)
{
    return PyPieAttributes_Check((PyObject *)pyobject);
}

// ****************************************************************************
// Method: PieScriptingPluginInfo::GetLogString
//
// Purpose:
//   Gets a string representation of the current attributes.
//
// Arguments:
//   val : Whether or not to log state information.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

char *
PieScriptingPluginInfo::GetLogString()
{
    std::string s(PyPieAttributes_GetLogString());
    char *v = new char[s.size() + 1];
    strcpy(v, s.c_str());
    return v;
}

// ****************************************************************************
// Method: PieScriptingPluginInfo::SetDefaults
//
// Purpose:
//   Used to set the default values for a plugin's state object.
//
// Arguments:
//   atts : The new state.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
PieScriptingPluginInfo::SetDefaults(const AttributeSubject *atts)
{
    PyPieAttributes_SetDefaults((const PieAttributes *)atts);
}
