// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: PieViewerPluginInfo.C
// ****************************************************************************

#include <PiePluginInfo.h>

VISIT_PLOT_PLUGIN_ENTRY_EV(Pie,Viewer)


// ****************************************************************************
//  Method: PieViewerPluginInfo::XPMIconData
//
//  Purpose:
//    Return a pointer to the icon data.
//
//  Returns:    A pointer to the icon data.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

#include <PiePlot.xpm>
const char **
PieViewerPluginInfo::XPMIconData() const
{
    return PiePlot_xpm;
}

