// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: PyPieAttributes.C
// ****************************************************************************

#include <PyPieAttributes.h>
#include <ObserverToCallback.h>
#include <stdio.h>
#include <Py2and3Support.h>
#include <PyColorAttributeList.h>

// ****************************************************************************
// Module: PyPieAttributes
//
// Purpose:
//   Attributes for the PiePlot plot.
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   omitted
//
// ****************************************************************************

//
// This struct contains the Python type information and a PieAttributes.
//
struct PieAttributesObject
{
    PyObject_HEAD
    PieAttributes *data;
    bool        owns;
    PyObject   *parent;
};

//
// Internal prototypes
//
static PyObject *NewPieAttributes(int);
std::string
PyPieAttributes_ToString(const PieAttributes *atts, const char *prefix)
{
    std::string str;
    char tmpStr[1000];

    const char *iGlyphStyle_names = "STYLE_PIE, STYLE_BAR, STYLE_BOX";
    switch (atts->GetIGlyphStyle())
    {
      case PieAttributes::STYLE_PIE:
          snprintf(tmpStr, 1000, "%siGlyphStyle = %sSTYLE_PIE  # %s\n", prefix, prefix, iGlyphStyle_names);
          str += tmpStr;
          break;
      case PieAttributes::STYLE_BAR:
          snprintf(tmpStr, 1000, "%siGlyphStyle = %sSTYLE_BAR  # %s\n", prefix, prefix, iGlyphStyle_names);
          str += tmpStr;
          break;
      case PieAttributes::STYLE_BOX:
          snprintf(tmpStr, 1000, "%siGlyphStyle = %sSTYLE_BOX  # %s\n", prefix, prefix, iGlyphStyle_names);
          str += tmpStr;
          break;
      default:
          break;
    }

    snprintf(tmpStr, 1000, "%siPieSectors = %d\n", prefix, atts->GetIPieSectors());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfPieRadius = %g\n", prefix, atts->GetFPieRadius());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfPieBorder = %g\n", prefix, atts->GetFPieBorder());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfBarXScale = %g\n", prefix, atts->GetFBarXScale());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfBarYScale = %g\n", prefix, atts->GetFBarYScale());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfBarBorder = %g\n", prefix, atts->GetFBarBorder());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfBoxXScale = %g\n", prefix, atts->GetFBoxXScale());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfBoxYScale = %g\n", prefix, atts->GetFBoxYScale());
    str += tmpStr;
    snprintf(tmpStr, 1000, "%sfBoxBorder = %g\n", prefix, atts->GetFBoxBorder());
    str += tmpStr;
    { const ColorAttributeList &cL = atts->GetMultiColor();
        const char *comment = (prefix==0 || strcmp(prefix,"")==0) ? "# " : "";
        for(int i = 0; i < cL.GetNumColors(); ++i)
        {
            const unsigned char *c = cL[i].GetColor();
            snprintf(tmpStr, 1000, "%s%sSetMultiColor(%d, (%d, %d, %d, %d))\n",
                     comment, prefix, i, int(c[0]), int(c[1]), int(c[2]), int(c[3]));
            str += tmpStr;
        }
    }
    return str;
}

static PyObject *
PieAttributes_Notify(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_SetIGlyphStyle(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    int ival;
    if(!PyArg_ParseTuple(args, "i", &ival))
        return NULL;

    // Set the iGlyphStyle in the object.
    if(ival >= 0 && ival < 3)
        obj->data->SetIGlyphStyle(PieAttributes::GlyphStyle(ival));
    else
    {
        fprintf(stderr, "An invalid iGlyphStyle value was given. "
                        "Valid values are in the range of [0,2]. "
                        "You can also use the following names: "
                        "STYLE_PIE, STYLE_BAR, STYLE_BOX.");
        return NULL;
    }

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetIGlyphStyle(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyInt_FromLong(long(obj->data->GetIGlyphStyle()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetIPieSectors(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    int ival;
    if(!PyArg_ParseTuple(args, "i", &ival))
        return NULL;

    // Set the iPieSectors in the object.
    obj->data->SetIPieSectors((int)ival);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetIPieSectors(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyInt_FromLong(long(obj->data->GetIPieSectors()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFPieRadius(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fPieRadius in the object.
    obj->data->SetFPieRadius(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFPieRadius(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFPieRadius()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFPieBorder(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fPieBorder in the object.
    obj->data->SetFPieBorder(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFPieBorder(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFPieBorder()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFBarXScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fBarXScale in the object.
    obj->data->SetFBarXScale(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFBarXScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFBarXScale()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFBarYScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fBarYScale in the object.
    obj->data->SetFBarYScale(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFBarYScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFBarYScale()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFBarBorder(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fBarBorder in the object.
    obj->data->SetFBarBorder(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFBarBorder(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFBarBorder()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFBoxXScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fBoxXScale in the object.
    obj->data->SetFBoxXScale(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFBoxXScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFBoxXScale()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFBoxYScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fBoxYScale in the object.
    obj->data->SetFBoxYScale(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFBoxYScale(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFBoxYScale()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetFBoxBorder(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the fBoxBorder in the object.
    obj->data->SetFBoxBorder(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetFBoxBorder(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetFBoxBorder()));
    return retval;
}

/*static*/ PyObject *
PieAttributes_SetMultiColor(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;

    PyObject *pyobj = NULL;
    ColorAttributeList &cL = obj->data->GetMultiColor();
    int index = 0;
    int c[4] = {0,0,0,255};
    bool setTheColor = true;

    if(!PyArg_ParseTuple(args, "iiiii", &index, &c[0], &c[1], &c[2], &c[3]))
    {
        if(!PyArg_ParseTuple(args, "iiii", &index, &c[0], &c[1], &c[2]))
        {
            double dr, dg, db, da;
            if(PyArg_ParseTuple(args, "idddd", &index, &dr, &dg, &db, &da))
            {
                c[0] = int(dr);
                c[1] = int(dg);
                c[2] = int(db);
                c[3] = int(da);
            }
            else if(PyArg_ParseTuple(args, "iddd", &index, &dr, &dg, &db))
            {
                c[0] = int(dr);
                c[1] = int(dg);
                c[2] = int(db);
                c[3] = 255;
            }
            else
            {
                if(!PyArg_ParseTuple(args, "iO", &index, &pyobj))
                {
                    if(PyArg_ParseTuple(args, "O", &pyobj))
                    {
                        setTheColor = false;
                        if(PyTuple_Check(pyobj))
                        {
                            // Make sure that the tuple is the right size.
                            if(PyTuple_Size(pyobj) < cL.GetNumColors())
                                return NULL;

                            // Make sure that the tuple is the right size.
                            bool badInput = false;
                            int *C = new int[4 * cL.GetNumColors()];
                            for(int i = 0; i < PyTuple_Size(pyobj) && !badInput; ++i)
                            {
                                PyObject *item = PyTuple_GET_ITEM(pyobj, i);
                                if(PyTuple_Check(item) &&
                                   (PyTuple_Size(item) == 3 || PyTuple_Size(item) == 4))
                                {
                                    C[i*4] = 0;
                                    C[i*4+1] = 0;
                                    C[i*4+2] = 0;
                                    C[i*4+3] = 255;
                                    for(int j = 0; j < PyTuple_Size(item) && !badInput; ++j)
                                    {
                                        PyObject *colorcomp = PyTuple_GET_ITEM(item, j);
                                        if(PyInt_Check(colorcomp))
                                           C[i*4+j] = int(PyInt_AS_LONG(colorcomp));
                                        else if(PyFloat_Check(colorcomp))
                                           C[i*4+j] = int(PyFloat_AS_DOUBLE(colorcomp));
                                        else
                                           badInput = true;
                                    }
                                }
                                else
                                    badInput = true;
                            }

                            if(badInput)
                            {
                                delete [] C;
                                return NULL;
                            }

                            for(int i = 0; i < cL.GetNumColors(); ++i)
                                cL[i].SetRgba(C[i*4], C[i*4+1], C[i*4+2], C[i*4+3]);
                            delete [] C;
                        }
                        else if(PyList_Check(pyobj))
                        {
                            // Make sure that the list is the right size.
                            if(PyList_Size(pyobj) < cL.GetNumColors())
                                return NULL;

                            // Make sure that the tuple is the right size.
                            bool badInput = false;
                            int *C = new int[4 * cL.GetNumColors()];
                            for(int i = 0; i < PyList_Size(pyobj) && !badInput; ++i)
                            {
                                PyObject *item = PyList_GET_ITEM(pyobj, i);
                                if(PyTuple_Check(item) &&
                                   (PyTuple_Size(item) == 3 || PyTuple_Size(item) == 4))
                                {
                                    C[i*4] = 0;
                                    C[i*4+1] = 0;
                                    C[i*4+2] = 0;
                                    C[i*4+3] = 255;
                                    for(int j = 0; j < PyTuple_Size(item) && !badInput; ++j)
                                    {
                                        PyObject *colorcomp = PyTuple_GET_ITEM(item, j);
                                        if(PyInt_Check(colorcomp))
                                           C[i*4+j] = int(PyInt_AS_LONG(colorcomp));
                                        else if(PyFloat_Check(colorcomp))
                                           C[i*4+j] = int(PyFloat_AS_DOUBLE(colorcomp));
                                        else
                                           badInput = true;
                                    }
                                }
                                else
                                    badInput = true;
                            }

                            if(badInput)
                            {
                                delete [] C;
                                return NULL;
                            }

                            for(int i = 0; i < cL.GetNumColors(); ++i)
                                cL[i].SetRgba(C[i*4], C[i*4+1], C[i*4+2], C[i*4+3]);

                            delete [] C;
                        }
                        else
                            return NULL;
                    }
                }
                else
                {
                    if(!PyTuple_Check(pyobj))
                        return NULL;

                    // Make sure that the tuple is the right size.
                    if(PyTuple_Size(pyobj) < 3 || PyTuple_Size(pyobj) > 4)
                        return NULL;

                    // Make sure that all elements in the tuple are ints.
                    for(int i = 0; i < PyTuple_Size(pyobj); ++i)
                    {
                        PyObject *item = PyTuple_GET_ITEM(pyobj, i);
                        if(PyInt_Check(item))
                            c[i] = int(PyInt_AS_LONG(PyTuple_GET_ITEM(pyobj, i)));
                        else if(PyFloat_Check(item))
                            c[i] = int(PyFloat_AS_DOUBLE(PyTuple_GET_ITEM(pyobj, i)));
                        else
                            return NULL;
                    }
                }
            }
        }
        PyErr_Clear();
    }

    if(index < 0 || index >= cL.GetNumColors())
        return NULL;

    // Set the color in the object.
    if(setTheColor)
        cL[index] = ColorAttribute(c[0], c[1], c[2], c[3]);
    cL.SelectColors();
    obj->data->SelectMultiColor();

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
PieAttributes_GetMultiColor(PyObject *self, PyObject *args)
{
    PieAttributesObject *obj = (PieAttributesObject *)self;
    PyObject *retval = NULL;
    ColorAttributeList &cL = obj->data->GetMultiColor();

    int index = 0;
    if(PyArg_ParseTuple(args, "i", &index))
    {
        if(index < 0 || index >= cL.GetNumColors())
            return NULL;

        // Allocate a tuple the with enough entries to hold the singleColor.
        retval = PyTuple_New(4);
        const unsigned char *c = cL.GetColors(index).GetColor();
        PyTuple_SET_ITEM(retval, 0, PyInt_FromLong(long(c[0])));
        PyTuple_SET_ITEM(retval, 1, PyInt_FromLong(long(c[1])));
        PyTuple_SET_ITEM(retval, 2, PyInt_FromLong(long(c[2])));
        PyTuple_SET_ITEM(retval, 3, PyInt_FromLong(long(c[3])));
    }
    else
    {
        PyErr_Clear();

        // Return the whole thing.
        retval = PyList_New(cL.GetNumColors());
        for(int i = 0; i < cL.GetNumColors(); ++i)
        {
            const unsigned char *c = cL.GetColors(i).GetColor();

            PyObject *t = PyTuple_New(4);
            PyTuple_SET_ITEM(t, 0, PyInt_FromLong(long(c[0])));
            PyTuple_SET_ITEM(t, 1, PyInt_FromLong(long(c[1])));
            PyTuple_SET_ITEM(t, 2, PyInt_FromLong(long(c[2])));
            PyTuple_SET_ITEM(t, 3, PyInt_FromLong(long(c[3])));

            PyList_SET_ITEM(retval, i, t);
        }
    }
    return retval;
}



PyMethodDef PyPieAttributes_methods[PIEATTRIBUTES_NMETH] = {
    {"Notify", PieAttributes_Notify, METH_VARARGS},
    {"SetIGlyphStyle", PieAttributes_SetIGlyphStyle, METH_VARARGS},
    {"GetIGlyphStyle", PieAttributes_GetIGlyphStyle, METH_VARARGS},
    {"SetIPieSectors", PieAttributes_SetIPieSectors, METH_VARARGS},
    {"GetIPieSectors", PieAttributes_GetIPieSectors, METH_VARARGS},
    {"SetFPieRadius", PieAttributes_SetFPieRadius, METH_VARARGS},
    {"GetFPieRadius", PieAttributes_GetFPieRadius, METH_VARARGS},
    {"SetFPieBorder", PieAttributes_SetFPieBorder, METH_VARARGS},
    {"GetFPieBorder", PieAttributes_GetFPieBorder, METH_VARARGS},
    {"SetFBarXScale", PieAttributes_SetFBarXScale, METH_VARARGS},
    {"GetFBarXScale", PieAttributes_GetFBarXScale, METH_VARARGS},
    {"SetFBarYScale", PieAttributes_SetFBarYScale, METH_VARARGS},
    {"GetFBarYScale", PieAttributes_GetFBarYScale, METH_VARARGS},
    {"SetFBarBorder", PieAttributes_SetFBarBorder, METH_VARARGS},
    {"GetFBarBorder", PieAttributes_GetFBarBorder, METH_VARARGS},
    {"SetFBoxXScale", PieAttributes_SetFBoxXScale, METH_VARARGS},
    {"GetFBoxXScale", PieAttributes_GetFBoxXScale, METH_VARARGS},
    {"SetFBoxYScale", PieAttributes_SetFBoxYScale, METH_VARARGS},
    {"GetFBoxYScale", PieAttributes_GetFBoxYScale, METH_VARARGS},
    {"SetFBoxBorder", PieAttributes_SetFBoxBorder, METH_VARARGS},
    {"GetFBoxBorder", PieAttributes_GetFBoxBorder, METH_VARARGS},
    {"SetMultiColor", PieAttributes_SetMultiColor, METH_VARARGS},
    {"GetMultiColor", PieAttributes_GetMultiColor, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
PieAttributes_dealloc(PyObject *v)
{
   PieAttributesObject *obj = (PieAttributesObject *)v;
   if(obj->parent != 0)
       Py_DECREF(obj->parent);
   if(obj->owns)
       delete obj->data;
}

static PyObject *PieAttributes_richcompare(PyObject *self, PyObject *other, int op);
PyObject *
PyPieAttributes_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "iGlyphStyle") == 0)
        return PieAttributes_GetIGlyphStyle(self, NULL);
    if(strcmp(name, "STYLE_PIE") == 0)
        return PyInt_FromLong(long(PieAttributes::STYLE_PIE));
    if(strcmp(name, "STYLE_BAR") == 0)
        return PyInt_FromLong(long(PieAttributes::STYLE_BAR));
    if(strcmp(name, "STYLE_BOX") == 0)
        return PyInt_FromLong(long(PieAttributes::STYLE_BOX));

    if(strcmp(name, "iPieSectors") == 0)
        return PieAttributes_GetIPieSectors(self, NULL);
    if(strcmp(name, "fPieRadius") == 0)
        return PieAttributes_GetFPieRadius(self, NULL);
    if(strcmp(name, "fPieBorder") == 0)
        return PieAttributes_GetFPieBorder(self, NULL);
    if(strcmp(name, "fBarXScale") == 0)
        return PieAttributes_GetFBarXScale(self, NULL);
    if(strcmp(name, "fBarYScale") == 0)
        return PieAttributes_GetFBarYScale(self, NULL);
    if(strcmp(name, "fBarBorder") == 0)
        return PieAttributes_GetFBarBorder(self, NULL);
    if(strcmp(name, "fBoxXScale") == 0)
        return PieAttributes_GetFBoxXScale(self, NULL);
    if(strcmp(name, "fBoxYScale") == 0)
        return PieAttributes_GetFBoxYScale(self, NULL);
    if(strcmp(name, "fBoxBorder") == 0)
        return PieAttributes_GetFBoxBorder(self, NULL);
    if(strcmp(name, "multiColor") == 0)
        return PieAttributes_GetMultiColor(self, NULL);

    return Py_FindMethod(PyPieAttributes_methods, self, name);
}

int
PyPieAttributes_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    PyObject *obj = NULL;

    if(strcmp(name, "iGlyphStyle") == 0)
        obj = PieAttributes_SetIGlyphStyle(self, tuple);
    else if(strcmp(name, "iPieSectors") == 0)
        obj = PieAttributes_SetIPieSectors(self, tuple);
    else if(strcmp(name, "fPieRadius") == 0)
        obj = PieAttributes_SetFPieRadius(self, tuple);
    else if(strcmp(name, "fPieBorder") == 0)
        obj = PieAttributes_SetFPieBorder(self, tuple);
    else if(strcmp(name, "fBarXScale") == 0)
        obj = PieAttributes_SetFBarXScale(self, tuple);
    else if(strcmp(name, "fBarYScale") == 0)
        obj = PieAttributes_SetFBarYScale(self, tuple);
    else if(strcmp(name, "fBarBorder") == 0)
        obj = PieAttributes_SetFBarBorder(self, tuple);
    else if(strcmp(name, "fBoxXScale") == 0)
        obj = PieAttributes_SetFBoxXScale(self, tuple);
    else if(strcmp(name, "fBoxYScale") == 0)
        obj = PieAttributes_SetFBoxYScale(self, tuple);
    else if(strcmp(name, "fBoxBorder") == 0)
        obj = PieAttributes_SetFBoxBorder(self, tuple);
    else if(strcmp(name, "multiColor") == 0)
        obj = PieAttributes_SetMultiColor(self, tuple);

    if(obj != NULL)
        Py_DECREF(obj);

    Py_DECREF(tuple);
    if( obj == NULL)
        PyErr_Format(PyExc_RuntimeError, "Unable to set unknown attribute: '%s'", name);
    return (obj != NULL) ? 0 : -1;
}

static int
PieAttributes_print(PyObject *v, FILE *fp, int flags)
{
    PieAttributesObject *obj = (PieAttributesObject *)v;
    fprintf(fp, "%s", PyPieAttributes_ToString(obj->data, "").c_str());
    return 0;
}

PyObject *
PieAttributes_str(PyObject *v)
{
    PieAttributesObject *obj = (PieAttributesObject *)v;
    return PyString_FromString(PyPieAttributes_ToString(obj->data,"").c_str());
}

//
// The doc string for the class.
//
#if PY_MAJOR_VERSION > 2 || (PY_MAJOR_VERSION == 2 && PY_MINOR_VERSION >= 5)
static const char *PieAttributes_Purpose = "Attributes for the PiePlot plot.";
#else
static char *PieAttributes_Purpose = "Attributes for the PiePlot plot.";
#endif

//
// Python Type Struct Def Macro from Py2and3Support.h
//
//         VISIT_PY_TYPE_OBJ( VPY_TYPE,
//                            VPY_NAME,
//                            VPY_OBJECT,
//                            VPY_DEALLOC,
//                            VPY_PRINT,
//                            VPY_GETATTR,
//                            VPY_SETATTR,
//                            VPY_STR,
//                            VPY_PURPOSE,
//                            VPY_RICHCOMP,
//                            VPY_AS_NUMBER)

//
// The type description structure
//

VISIT_PY_TYPE_OBJ(PieAttributesType,         \
                  "PieAttributes",           \
                  PieAttributesObject,       \
                  PieAttributes_dealloc,     \
                  PieAttributes_print,       \
                  PyPieAttributes_getattr,   \
                  PyPieAttributes_setattr,   \
                  PieAttributes_str,         \
                  PieAttributes_Purpose,     \
                  PieAttributes_richcompare, \
                  0); /* as_number*/

//
// Helper function for comparing.
//
static PyObject *
PieAttributes_richcompare(PyObject *self, PyObject *other, int op)
{
    // only compare against the same type 
    if ( Py_TYPE(self) != &PieAttributesType
         || Py_TYPE(other) != &PieAttributesType)
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    PyObject *res = NULL;
    PieAttributes *a = ((PieAttributesObject *)self)->data;
    PieAttributes *b = ((PieAttributesObject *)other)->data;

    switch (op)
    {
       case Py_EQ:
           res = (*a == *b) ? Py_True : Py_False;
           break;
       case Py_NE:
           res = (*a != *b) ? Py_True : Py_False;
           break;
       default:
           res = Py_NotImplemented;
           break;
    }

    Py_INCREF(res);
    return res;
}

//
// Helper functions for object allocation.
//

static PieAttributes *defaultAtts = 0;
static PieAttributes *currentAtts = 0;

static PyObject *
NewPieAttributes(int useCurrent)
{
    PieAttributesObject *newObject;
    newObject = PyObject_NEW(PieAttributesObject, &PieAttributesType);
    if(newObject == NULL)
        return NULL;
    if(useCurrent && currentAtts != 0)
        newObject->data = new PieAttributes(*currentAtts);
    else if(defaultAtts != 0)
        newObject->data = new PieAttributes(*defaultAtts);
    else
        newObject->data = new PieAttributes;
    newObject->owns = true;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

static PyObject *
WrapPieAttributes(const PieAttributes *attr)
{
    PieAttributesObject *newObject;
    newObject = PyObject_NEW(PieAttributesObject, &PieAttributesType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (PieAttributes *)attr;
    newObject->owns = false;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
PieAttributes_new(PyObject *self, PyObject *args)
{
    int useCurrent = 0;
    if (!PyArg_ParseTuple(args, "i", &useCurrent))
    {
        if (!PyArg_ParseTuple(args, ""))
            return NULL;
        else
            PyErr_Clear();
    }

    return (PyObject *)NewPieAttributes(useCurrent);
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef PieAttributesMethods[] = {
    {"PieAttributes", PieAttributes_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *PieAttributesObserver = 0;

std::string
PyPieAttributes_GetLogString()
{
    std::string s("PieAtts = PieAttributes()\n");
    if(currentAtts != 0)
        s += PyPieAttributes_ToString(currentAtts, "PieAtts.");
    return s;
}

static void
PyPieAttributes_CallLogRoutine(Subject *subj, void *data)
{
    typedef void (*logCallback)(const std::string &);
    logCallback cb = (logCallback)data;

    if(cb != 0)
    {
        std::string s("PieAtts = PieAttributes()\n");
        s += PyPieAttributes_ToString(currentAtts, "PieAtts.");
        cb(s);
    }
}

void
PyPieAttributes_StartUp(PieAttributes *subj, void *data)
{
    if(subj == 0)
        return;

    currentAtts = subj;
    PyPieAttributes_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(PieAttributesObserver == 0)
    {
        PieAttributesObserver = new ObserverToCallback(subj,
            PyPieAttributes_CallLogRoutine, (void *)data);
    }

}

void
PyPieAttributes_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete PieAttributesObserver;
    PieAttributesObserver = 0;
}

PyMethodDef *
PyPieAttributes_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return PieAttributesMethods;
}

bool
PyPieAttributes_Check(PyObject *obj)
{
    return (obj->ob_type == &PieAttributesType);
}

PieAttributes *
PyPieAttributes_FromPyObject(PyObject *obj)
{
    PieAttributesObject *obj2 = (PieAttributesObject *)obj;
    return obj2->data;
}

PyObject *
PyPieAttributes_New()
{
    return NewPieAttributes(0);
}

PyObject *
PyPieAttributes_Wrap(const PieAttributes *attr)
{
    return WrapPieAttributes(attr);
}

void
PyPieAttributes_SetParent(PyObject *obj, PyObject *parent)
{
    PieAttributesObject *obj2 = (PieAttributesObject *)obj;
    obj2->parent = parent;
}

void
PyPieAttributes_SetDefaults(const PieAttributes *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new PieAttributes(*atts);
}

