// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: QvisPiePlotWindow.C
// ****************************************************************************

#include "QvisPiePlotWindow.h"

#include <PieAttributes.h>
#include <ViewerProxy.h>

#include <QGroupBox>
#include <QCheckBox>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QSpinBox>
#include <QButtonGroup>
#include <QRadioButton>
#include <QColor>
#include <QvisColorTableButton.h>
#include <QvisOpacitySlider.h>
#include <QvisColorButton.h>
#include <QvisLineWidthWidget.h>
#include <QvisVariableButton.h>
#include <QvisColorManagerWidget.h>

#include <DebugStream.h>
#include "GlyphColors.h"


// ****************************************************************************
// Method: QvisPiePlotWindow::QvisPiePlotWindow
//
// Purpose:
//   Constructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

QvisPiePlotWindow::QvisPiePlotWindow(const int type,
                         PieAttributes *subj,
                         const QString &caption,
                         const QString &shortName,
                         QvisNotepadArea *notepad)
    : QvisPostableWindowObserver(subj, caption, shortName, notepad)
{
    plotType = type;
    atts = subj;
    debug1 << "QHG: [QvisPiePlotWindow::QvisPiePlotWindow] atts (" << atts <<") has" << atts->GetValueNames().size() << " names" <<endl << std::flush; 
}


// ****************************************************************************
// Method: QvisPiePlotWindow::~QvisPiePlotWindow
//
// Purpose:
//   Destructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

QvisPiePlotWindow::~QvisPiePlotWindow()
{
    debug1 << "QHG: [QvisPiePlotWindow::QvisPiePlotWindow] is deleted (" << atts <<") has" << atts->GetValueNames().size() << " names" <<endl << std::flush; 

}


// ****************************************************************************
// Method: QvisPiePlotWindow::CreateWindowContents
//
// Purpose:
//   Creates the widgets for the window.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::CreateWindowContents()
{
    QGridLayout *mainLayout = new QGridLayout(0);
    topLayout->addLayout(mainLayout);

    iGlyphStyleLabel = new QLabel(tr("Glyph Style"), central);
    mainLayout->addWidget(iGlyphStyleLabel,0,0);
    iGlyphStyle = new QWidget(central);
    iGlyphStyleButtonGroup= new QButtonGroup(iGlyphStyle);
    QHBoxLayout *iGlyphStyleLayout = new QHBoxLayout(iGlyphStyle);
    iGlyphStyleLayout->setMargin(0);
    iGlyphStyleLayout->setSpacing(10);
    QRadioButton *iGlyphStyleGlyphStyleSTYLE_PIE = new QRadioButton(tr("STYLE_PIE"), iGlyphStyle);
    iGlyphStyleButtonGroup->addButton(iGlyphStyleGlyphStyleSTYLE_PIE,0);
    iGlyphStyleLayout->addWidget(iGlyphStyleGlyphStyleSTYLE_PIE);
    QRadioButton *iGlyphStyleGlyphStyleSTYLE_BAR = new QRadioButton(tr("STYLE_BAR"), iGlyphStyle);
    iGlyphStyleButtonGroup->addButton(iGlyphStyleGlyphStyleSTYLE_BAR,1);
    iGlyphStyleLayout->addWidget(iGlyphStyleGlyphStyleSTYLE_BAR);
    QRadioButton *iGlyphStyleGlyphStyleSTYLE_BOX = new QRadioButton(tr("STYLE_BOX"), iGlyphStyle);
    iGlyphStyleButtonGroup->addButton(iGlyphStyleGlyphStyleSTYLE_BOX,2);
    iGlyphStyleLayout->addWidget(iGlyphStyleGlyphStyleSTYLE_BOX);
    connect(iGlyphStyleButtonGroup, SIGNAL(buttonClicked(int)),
            this, SLOT(iGlyphStyleChanged(int)));
    mainLayout->addWidget(iGlyphStyle, 0,1);

    iPieSectorsLabel = new QLabel(tr("Num Sectors"), central);
    mainLayout->addWidget(iPieSectorsLabel,1,0);
    iPieSectors = new QLineEdit(central);
    connect(iPieSectors, SIGNAL(returnPressed()),
            this, SLOT(iPieSectorsProcessText()));
    mainLayout->addWidget(iPieSectors, 1,1);

    fPieRadiusLabel = new QLabel(tr("Pie Radius"), central);
    mainLayout->addWidget(fPieRadiusLabel,2,0);
    fPieRadius = new QLineEdit(central);
    connect(fPieRadius, SIGNAL(returnPressed()),
            this, SLOT(fPieRadiusProcessText()));
    mainLayout->addWidget(fPieRadius, 2,1);

    fPieBorderLabel = new QLabel(tr("Border Width"), central);
    mainLayout->addWidget(fPieBorderLabel,3,0);
    fPieBorder = new QLineEdit(central);
    connect(fPieBorder, SIGNAL(returnPressed()),
            this, SLOT(fPieBorderProcessText()));
    mainLayout->addWidget(fPieBorder, 3,1);

    fBarXScaleLabel = new QLabel(tr("Scale X"), central);
    mainLayout->addWidget(fBarXScaleLabel,4,0);
    fBarXScale = new QLineEdit(central);
    connect(fBarXScale, SIGNAL(returnPressed()),
            this, SLOT(fBarXScaleProcessText()));
    mainLayout->addWidget(fBarXScale, 4,1);

    fBarYScaleLabel = new QLabel(tr("Scale Y"), central);
    mainLayout->addWidget(fBarYScaleLabel,5,0);
    fBarYScale = new QLineEdit(central);
    connect(fBarYScale, SIGNAL(returnPressed()),
            this, SLOT(fBarYScaleProcessText()));
    mainLayout->addWidget(fBarYScale, 5,1);

    fBarBorderLabel = new QLabel(tr("Border Width"), central);
    mainLayout->addWidget(fBarBorderLabel,6,0);
    fBarBorder = new QLineEdit(central);
    connect(fBarBorder, SIGNAL(returnPressed()),
            this, SLOT(fBarBorderProcessText()));
    mainLayout->addWidget(fBarBorder, 6,1);

    fBoxXScaleLabel = new QLabel(tr("Scale X"), central);
    mainLayout->addWidget(fBoxXScaleLabel,7,0);
    fBoxXScale = new QLineEdit(central);
    connect(fBoxXScale, SIGNAL(returnPressed()),
            this, SLOT(fBoxXScaleProcessText()));
    mainLayout->addWidget(fBoxXScale, 7,1);

    fBoxYScaleLabel = new QLabel(tr("Scale Y"), central);
    mainLayout->addWidget(fBoxYScaleLabel,8,0);
    fBoxYScale = new QLineEdit(central);
    connect(fBoxYScale, SIGNAL(returnPressed()),
            this, SLOT(fBoxYScaleProcessText()));
    mainLayout->addWidget(fBoxYScale, 8,1);

    fBoxBorderLabel = new QLabel(tr("Border Width"), central);
    mainLayout->addWidget(fBoxBorderLabel,9,0);
    fBoxBorder = new QLineEdit(central);
    connect(fBoxBorder, SIGNAL(returnPressed()),
            this, SLOT(fBoxBorderProcessText()));
    mainLayout->addWidget(fBoxBorder, 9,1);

    QGroupBox * glyphColorGroup = new QGroupBox(central);
    glyphColorGroup->setTitle(tr("Glyph Colors"));
    topLayout->addWidget(glyphColorGroup);
    topLayout->setStretchFactor(glyphColorGroup, 100);

    QGridLayout *colorLayout = new QGridLayout(glyphColorGroup);
    colorLayout->setMargin(5);
    colorLayout->setSpacing(10);

    // Add the multiple colors widget.
    multipleColors = new QvisColorManagerWidget(glyphColorGroup);
    multipleColors->setNameLabelText(tr("Item"));

 
    // here we'd like the attribute to have the value names, and then fill them here
    debug1 << "QHG: [QvisPiePlotWindow::CreateWindowContents] atts (" << atts <<") has" << atts->GetValueNames().size() << " names" <<endl << std::flush; 
    const std::vector<std::string> &vNames = atts->GetValueNames();
    
    uint iNumCols = vNames.size();
    debug1 << "QHG: [QvisPiePlotWindow::CreateWindowContents] found " << iNumCols << "value names" << endl << std::flush;
     
    for (int i = 0; i < iNumCols; i++) {
        // here we silently assume that vasic_colors has enough colors
        QColor qc{qRgb(basic_colors[i+1][0], basic_colors[i+1][1], basic_colors[i+1][2])};
        
        debug1 << "QHG: [QvisPiePlotWindow::CreateWindowContents] setting string #" << i << endl << std::flush;
        debug1 << " [" << vNames[i] << "]" << endl << std::flush;
        QString qs = vNames[i].c_str();
        multipleColors->addEntry(qs, qc, 255);   
    }

    connect(multipleColors, SIGNAL(colorChanged(const QColor &, int)),
            this, SLOT(multipleColorChanged(const QColor &, int)));
    colorLayout->addWidget(multipleColors, 1, 0, 1, 3);

}


// ****************************************************************************
// Method: QvisPiePlotWindow::UpdateWindow
//
// Purpose:
//   Updates the widgets in the window when the subject changes.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::UpdateWindow(bool doAll)
{

    for(int i = 0; i < atts->NumAttributes(); ++i)
    {
        if(!doAll)
        {
            if(!atts->IsSelected(i))
            {
                continue;
            }
        }

        switch(i)
        {
          case PieAttributes::ID_iGlyphStyle:
            iGlyphStyleButtonGroup->blockSignals(true);
            if(iGlyphStyleButtonGroup->button((int)atts->GetIGlyphStyle()) != 0)
                iGlyphStyleButtonGroup->button((int)atts->GetIGlyphStyle())->setChecked(true);
            iGlyphStyleButtonGroup->blockSignals(false);
            break;
          case PieAttributes::ID_iPieSectors:
            iPieSectors->setText(IntToQString(atts->GetIPieSectors()));
            break;
          case PieAttributes::ID_fPieRadius:
            fPieRadius->setText(FloatToQString(atts->GetFPieRadius()));
            break;
          case PieAttributes::ID_fPieBorder:
            fPieBorder->setText(FloatToQString(atts->GetFPieBorder()));
            break;
          case PieAttributes::ID_fBarXScale:
            fBarXScale->setText(FloatToQString(atts->GetFBarXScale()));
            break;
          case PieAttributes::ID_fBarYScale:
            fBarYScale->setText(FloatToQString(atts->GetFBarYScale()));
            break;
          case PieAttributes::ID_fBarBorder:
            fBarBorder->setText(FloatToQString(atts->GetFBarBorder()));
            break;
          case PieAttributes::ID_fBoxXScale:
            fBoxXScale->setText(FloatToQString(atts->GetFBoxXScale()));
            break;
          case PieAttributes::ID_fBoxYScale:
            fBoxYScale->setText(FloatToQString(atts->GetFBoxYScale()));
            break;
          case PieAttributes::ID_fBoxBorder:
            fBoxBorder->setText(FloatToQString(atts->GetFBoxBorder()));
            break;
          case PieAttributes::ID_multiColor:
        //writeSourceUpdate unknown for att (variable multiColor)
            break;
        }
    }


    switch (atts->GetIGlyphStyle()) {
    case PieAttributes::STYLE_PIE:
        iPieSectors->show();
        fPieRadius->show();
        fPieBorder->show();
        iPieSectorsLabel->show();
        fPieRadiusLabel->show();
        fPieBorderLabel->show();

        fBarXScale->hide();
        fBarYScale->hide();
        fBarBorder->hide();
        fBarXScaleLabel->hide();
        fBarYScaleLabel->hide();
        fBarBorderLabel->hide();

        fBoxXScale->hide();
	fBoxYScale->hide(); 
        fBoxBorder->hide();
        fBoxXScaleLabel->hide();
        fBoxYScaleLabel->hide();
        fBoxBorderLabel->hide();
        break;

    case PieAttributes::STYLE_BAR:
        iPieSectors->hide();
        fPieRadius->hide();
        fPieBorder->hide();
        iPieSectorsLabel->hide();
        fPieRadiusLabel->hide();
        fPieBorderLabel->hide();

        fBarXScale->show();
        fBarYScale->show();
        fBarBorder->show();
        fBarXScaleLabel->show();
        fBarYScaleLabel->show();
        fBarBorderLabel->show();

        fBoxXScale->hide();
	fBoxYScale->hide(); 
        fBoxBorder->hide();
        fBoxXScaleLabel->hide();
        fBoxYScaleLabel->hide();
        fBoxBorderLabel->hide();
        break;
    case PieAttributes::STYLE_BOX:
        iPieSectors->hide();
        fPieRadius->hide();
        fPieBorder->hide();
        iPieSectorsLabel->hide();
        fPieRadiusLabel->hide();
        fPieBorderLabel->hide();

        fBarXScale->hide();
        fBarYScale->hide();
        fBarBorder->hide();
        fBarXScaleLabel->hide();
        fBarYScaleLabel->hide();
        fBarBorderLabel->hide();

        fBoxXScale->show();
        fBoxYScale->show();
        fBoxBorder->show();
        fBoxXScaleLabel->show();
        fBoxYScaleLabel->show();
        fBoxBorderLabel->show();
        break;
    default:
        debug1 << "unknown glyph type (should not happen)" << endl <<std::flush;
    }

    UpdateMultipleAreaNames();
}


// ****************************************************************************
// Method: QvisPiePlotWindow::GetCurrentValues
//
// Purpose:
//   Gets values from certain widgets and stores them in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::GetCurrentValues(int which_widget)
{
    bool doAll = (which_widget == -1);

    // Do iPieSectors
    if(which_widget == PieAttributes::ID_iPieSectors || doAll)
    {
        int val;
        if(LineEditGetInt(iPieSectors, val))
            atts->SetIPieSectors(val);
        else
        {
            ResettingError(tr("Num Sectors"),
                IntToQString(atts->GetIPieSectors()));
            atts->SetIPieSectors(atts->GetIPieSectors());
        }
    }

    // Do fPieRadius
    if(which_widget == PieAttributes::ID_fPieRadius || doAll)
    {
        float val;
        if(LineEditGetFloat(fPieRadius, val))
            atts->SetFPieRadius(val);
        else
        {
            ResettingError(tr("Pie Radius"),
                FloatToQString(atts->GetFPieRadius()));
            atts->SetFPieRadius(atts->GetFPieRadius());
        }
    }

    // Do fPieBorder
    if(which_widget == PieAttributes::ID_fPieBorder || doAll)
    {
        float val;
        if(LineEditGetFloat(fPieBorder, val))
            atts->SetFPieBorder(val);
        else
        {
            ResettingError(tr("Border Width"),
                FloatToQString(atts->GetFPieBorder()));
            atts->SetFPieBorder(atts->GetFPieBorder());
        }
    }

    // Do fBarXScale
    if(which_widget == PieAttributes::ID_fBarXScale || doAll)
    {
        float val;
        if(LineEditGetFloat(fBarXScale, val))
            atts->SetFBarXScale(val);
        else
        {
            ResettingError(tr("Scale X"),
                FloatToQString(atts->GetFBarXScale()));
            atts->SetFBarXScale(atts->GetFBarXScale());
        }
    }

    // Do fBarYScale
    if(which_widget == PieAttributes::ID_fBarYScale || doAll)
    {
        float val;
        if(LineEditGetFloat(fBarYScale, val))
            atts->SetFBarYScale(val);
        else
        {
            ResettingError(tr("Scale Y"),
                FloatToQString(atts->GetFBarYScale()));
            atts->SetFBarYScale(atts->GetFBarYScale());
        }
    }

    // Do fBarBorder
    if(which_widget == PieAttributes::ID_fBarBorder || doAll)
    {
        float val;
        if(LineEditGetFloat(fBarBorder, val))
            atts->SetFBarBorder(val);
        else
        {
            ResettingError(tr("Border Width"),
                FloatToQString(atts->GetFBarBorder()));
            atts->SetFBarBorder(atts->GetFBarBorder());
        }
    }

    // Do fBoxXScale
    if(which_widget == PieAttributes::ID_fBoxXScale || doAll)
    {
        float val;
        if(LineEditGetFloat(fBoxXScale, val))
            atts->SetFBoxXScale(val);
        else
        {
            ResettingError(tr("Scale X"),
                FloatToQString(atts->GetFBoxXScale()));
            atts->SetFBoxXScale(atts->GetFBoxXScale());
        }
    }

    // Do fBoxYScale
    if(which_widget == PieAttributes::ID_fBoxYScale || doAll)
    {
        float val;
        if(LineEditGetFloat(fBoxYScale, val))
            atts->SetFBoxYScale(val);
        else
        {
            ResettingError(tr("Scale Y"),
                FloatToQString(atts->GetFBoxYScale()));
            atts->SetFBoxYScale(atts->GetFBoxYScale());
        }
    }

    // Do fBoxBorder
    if(which_widget == PieAttributes::ID_fBoxBorder || doAll)
    {
        float val;
        if(LineEditGetFloat(fBoxBorder, val))
            atts->SetFBoxBorder(val);
        else
        {
            ResettingError(tr("Border Width"),
                FloatToQString(atts->GetFBoxBorder()));
            atts->SetFBoxBorder(atts->GetFBoxBorder());
        }
    }

}


// ****************************************************************************
// Method: QvisPiePlotWindow::Apply
//
// Purpose:
//   Called to apply changes in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::Apply(bool ignore)
{
    if(AutoUpdate() || ignore)
    {
        GetCurrentValues(-1);
        atts->Notify();

        GetViewerMethods()->SetPlotOptions(plotType);
    }
    else
        atts->Notify();
}


//
// Qt Slot functions
//


// ****************************************************************************
// Method: QvisPiePlotWindow::apply
//
// Purpose:
//   Qt slot function called when apply button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::apply()
{
    Apply(true);
}


// ****************************************************************************
// Method: QvisPiePlotWindow::makeDefault
//
// Purpose:
//   Qt slot function called when "Make default" button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::makeDefault()
{
    GetCurrentValues(-1);
    atts->Notify();
    GetViewerMethods()->SetDefaultPlotOptions(plotType);
}


// ****************************************************************************
// Method: QvisPiePlotWindow::reset
//
// Purpose:
//   Qt slot function called when reset button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//
// ****************************************************************************

void
QvisPiePlotWindow::reset()
{
    GetViewerMethods()->ResetPlotOptions(plotType);
}


void
QvisPiePlotWindow::iGlyphStyleChanged(int val)
{
    if(val != atts->GetIGlyphStyle())
    {
        atts->SetIGlyphStyle(PieAttributes::GlyphStyle(val));
        SetUpdate(true);
        Apply();
    }
}


void
QvisPiePlotWindow::iPieSectorsProcessText()
{
    GetCurrentValues(PieAttributes::ID_iPieSectors);
    Apply();
}


void
QvisPiePlotWindow::fPieRadiusProcessText()
{
    GetCurrentValues(PieAttributes::ID_fPieRadius);
    Apply();
}


void
QvisPiePlotWindow::fPieBorderProcessText()
{
    GetCurrentValues(PieAttributes::ID_fPieBorder);
    Apply();
}


void
QvisPiePlotWindow::fBarXScaleProcessText()
{
    GetCurrentValues(PieAttributes::ID_fBarXScale);
    Apply();
}


void
QvisPiePlotWindow::fBarYScaleProcessText()
{
    GetCurrentValues(PieAttributes::ID_fBarYScale);
    Apply();
}


void
QvisPiePlotWindow::fBarBorderProcessText()
{
    GetCurrentValues(PieAttributes::ID_fBarBorder);
    Apply();
}


void
QvisPiePlotWindow::fBoxXScaleProcessText()
{
    GetCurrentValues(PieAttributes::ID_fBoxXScale);
    Apply();
}


void
QvisPiePlotWindow::fBoxYScaleProcessText()
{
    GetCurrentValues(PieAttributes::ID_fBoxYScale);
    Apply();
}


void
QvisPiePlotWindow::fBoxBorderProcessText()
{
    GetCurrentValues(PieAttributes::ID_fBoxBorder);
    Apply();
}


// ****************************************************************************
// Method: QvisPiePlotWindow::multipleColorChanged
//
// Purpose: 
//   This is a Qt slot function that is called when a new color is selected
//   for one of the color buttons in the multiple colors area.
//
// Arguments:
//   color : The new color for the button.
//   index : The index of the color that changed.
// 
// Programmer: Brad Whitlock
// Creation:   Sat Feb 17 13:42:22 PST 2001
//
// Modifications:
//   Brad Whitlock, Fri Mar 30 19:18:25 PST 2001
//   Made it conform to ContourAttribute's new interface.
//
//   Brad Whitlock, Mon Dec 9 11:01:45 PDT 2002
//   Added code to mark the color as having been changed.
//
// ****************************************************************************
void
QvisPiePlotWindow::multipleColorChanged(const QColor &color, int index)
{
    debug1 << "QHG:[QvisPiePlotWindow::multipleColorChanged] color ("<<color.red()<<","<< color.green()<<","<< color.blue()<<") for index "<<index<<endl<<std::flush;
    debug1 << "QHG:[QvisPiePlotWindow::multipleColorChanged] att numcolors is "<< atts->GetMultiColor().GetNumColors() <<endl<<std::flush;
    if((index >= 0) &&
        (index < atts->GetMultiColor().GetNumColors()))
    {
        const ColorAttribute &ca = atts->GetMultiColor()[index];
        debug1 << "QHG:[QvisPiePlotWindow::multipleColorChanged] color@"<<index<<": ("<<ca.Red()<<","<< ca.Green()<<","<< ca.Blue()<<")" <<endl<<std::flush;
        atts->GetMultiColor()[index].SetRgb(color.red(), color.green(),
                                                   color.blue());
        atts->SelectMultiColor();
        //        atts->MarkColorAsChanged(index);

        Apply();
    }
}


// ****************************************************************************
// Method: QvisContourPlotWindow::UpdateMultipleAreaNames
//
// Purpose: 
//   This method updates the multipleColors widget with the list of contour
//   names.
//
// Programmer: Brad Whitlock
// Creation:   Sat Feb 17 13:42:22 PST 2001
//
// Modifications:
//   Brad Whitlock, Thu Aug 22 12:31:51 PDT 2002
//   I made it return true if the widget should be enabled.
//
// ****************************************************************************

bool
QvisPiePlotWindow::UpdateMultipleAreaNames()
{
    QString temp;
    int     i, vecSize;

    const std::vector<std::string> &vNames = atts->GetValueNames();
    vecSize = vNames.size();
    debug1 << "[QvisPiePlotWindow::UpdateMultipleAreaNames()] got num vals " << vecSize << endl <<std::flush;
    debug1 << "[QvisPiePlotWindow::UpdateMultipleAreaNames()] num entries " <<  multipleColors->numEntries() << endl <<std::flush;
    if(vecSize == multipleColors->numEntries())
    {
        for(i = 0; i < vecSize; ++i)
        {
            QString temp(vNames[i].c_str());
            multipleColors->setAttributeName(i, temp);
        }
    }
    else if(vecSize > multipleColors->numEntries())
    {
        // Set all of the existing names.
        for(i = 0; i < multipleColors->numEntries(); ++i)
        {
            QString  temp(vNames[i].c_str());
            multipleColors->setAttributeName(i, temp);
        }

        // Add new entries
        for(i = multipleColors->numEntries(); i < vecSize; ++i)
        {
            QString temp(vNames[i].c_str());
            multipleColors->addEntry(temp, QColor(0,0,0), 255);
        }
    }
    else // if(vecSize < multipleColors->numEntries())
    {
        // Set all of the existing names.
        for(i = 0; i < vecSize; ++i)
        {
            QString temp(vNames[i].c_str());
            multipleColors->setAttributeName(i, temp);
        }

        // Remove excess entries
        int numEntries = multipleColors->numEntries();
        for(i = vecSize; i < numEntries; ++i)
        {
            multipleColors->removeLastEntry();
        }
    }

    return (vecSize > 0);
}

// ****************************************************************************
// Method: QvisContourPlotWindow::LevelString
//
// Purpose: 
//   Returns a string version of the data value that we want.
//
// Arguments:
//   i : The index of the data value that we want to use.
//
// Returns:    A string version of the data value that we want.
//
// Programmer: Brad Whitlock
// Creation:   Fri Feb 16 14:18:36 PST 2001
//
// Modifications:
//   Jeremy Meredith, Tue Nov 16 11:39:53 PST 2004
//   Replaced simple QString::sprintf's with a setNum because there seems
//   to be a bug causing numbers to be incremented by .00001.  See '5263.
//
//   Kathleen Biagas, Thu Apr 9 07:19:54 MST 2015
//   Use helper function DoubleToQString for consistency in formatting across
//   all windows.
//
// ****************************************************************************

QString
QvisPiePlotWindow::LevelString(int i)
{
    QString retval("");

    retval  = "itemolo "+IntToQString(i+1);

    return retval;
}
