CORE=../core
UTILS =../utils
UTILS_QHG=../utils_qhg
GEOINFO=../geoinfo
TILING=../tiling 
IMPORT=../import
ICOSA=../icosa
IO=../io
ACTIONS=../actions
POPULATIONS=../populations
DYNPOPS=../dynpops
GROUPS=../groups

USEFUL=../useful_stuff
GENES=../genes
TOOLS_IO=../tools_io
TOOLS_ICO=../tools_ico
TOOLS_QDF=../tools_qdf
VISUAL=../visual
