REVISION_H="../utils/svn_revision.h"

echo "#ifndef __SVN_REVISION_H__"                  > ${REVISION_H}
echo "#define __SVN_REVISION_H__"                 >> ${REVISION_H}
echo "// this file is generated by configure.sh"  >> ${REVISION_H}
echo "static const char REVISION[] = \"${REV}\";" >> ${REVISION_H}
echo "#endif"                                     >> ${REVISION_H}

